info:
  component: Single Swagger Document Server for multiple services
spring:
  profiles: default
server:
  port: 8080
documentation:
  swagger:
    config:
      refreshrate: 60000
    services:
    - name: ${serviceName1}
      serviceUrl: http://localhost:8080/api-doc/${serviceName1}
      swaggerServiceUrl: ${swaggerDocumentationURIForService1}
      version: 2.0
    - name: ${serviceName2}
      serviceUrl: http://localhost:8080/api-doc/${serviceName2}
      swaggerServiceUrl: ${swaggerDocumentationURIForService2}
      version: 2.0
    - name: ${serviceName3}
      serviceUrl: http://localhost:8080/api-doc/${serviceName3}
      swaggerServiceUrl: ${swaggerDocumentationURIForService3}
      version: 2.0
